импорт таблицы через url, берем первую таблицу [0]

In [3]:
import pandas as pd

In [43]:
df = pd.read_html("https://pstu.ru/files/file/Abitur/2025%20final/%D0%A4%D0%9F%D0%9C%D0%9C_%D0%91_%D0%9D_000007052.html")[0]
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,Списки поступающих,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,Дата формирования - 14.08.2025. Время формиров...,NaN,NaN
3,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,Форма обучения - Очная,NaN,NaN
4,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,Подразделение - Факультет прикладной математик...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,58,3940951,203,64,70,69,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
71,59,3884003,203,58,72,73,0,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
72,60,4532678,202,74,64,64,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
73,61,4076891,202,55,65,82,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
74,62,4395079,200,70,60,70,0,ИСТ -25-3б,№ 11-08/5-С от 11.08.2025,NaN,NaN,NaN,NaN

убираем лишние строки сверху

In [44]:
df = df.iloc[13:]
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
13,1,3839999,248,82,83,83,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
14,2,4841617,243,90,80,73,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
15,3,3950298,243,76,84,83,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
16,4,3804419,242,82,78,82,0,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
17,5,3694554,241,70,85,81,5,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,58,3940951,203,64,70,69,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
71,59,3884003,203,58,72,73,0,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
72,60,4532678,202,74,64,64,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
73,61,4076891,202,55,65,82,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025,NaN,NaN,NaN,NaN
74,62,4395079,200,70,60,70,0,ИСТ -25-3б,№ 11-08/5-С от 11.08.2025,NaN,NaN,NaN,NaN

убираем пустые столбцы (axis=1 - работаем по столбцам, how="all" - удаляем только те столбцы, где все пустые значения)

In [45]:
df = df.dropna(axis=1, how="all")
df

     0        1    2   3   4   5  6           7                           8
13   1  3839999  248  82  83  83  0  ИСТ -25-1б  № 07-08/10-С от 07.08.2025
14   2  4841617  243  90  80  73  0  ИСТ -25-2б  № 07-08/10-С от 07.08.2025
15   3  3950298  243  76  84  83  0  ИСТ -25-1б  № 07-08/10-С от 07.08.2025
16   4  3804419  242  82  78  82  0  ИСТ -25-3б  № 07-08/10-С от 07.08.2025
17   5  3694554  241  70  85  81  5  ИСТ -25-3б  № 07-08/10-С от 07.08.2025
..  ..      ...  ...  ..  ..  .. ..         ...                         ...
70  58  3940951  203  64  70  69  0  ИСТ -25-2б  № 07-08/10-С от 07.08.2025
71  59  3884003  203  58  72  73  0  ИСТ -25-3б  № 07-08/10-С от 07.08.2025
72  60  4532678  202  74  64  64  0  ИСТ -25-1б  № 07-08/10-С от 07.08.2025
73  61  4076891  202  55  65  82  0  ИСТ -25-2б  № 07-08/10-С от 07.08.2025
74  62  4395079  200  70  60  70  0  ИСТ -25-3б   № 11-08/5-С от 11.08.2025

[62 rows x 9 columns]

переименовываем столбцы

In [40]:
df.columns = ["№",	"Уникальный код",	"Сумма баллов",	"АиНМА / Математика",	"ИТ / Информатика и ИКТ / Физика",	"Русский язык",	"Сумма баллов за ИД",	"Учебная группа",	"Представление приказа"]
df

,№,Уникальный код,Сумма баллов,АиНМА / Математика,ИТ / Информатика и ИКТ / Физика,Русский язык,Сумма баллов за ИД,Учебная группа,Представление приказа
13,1,3839999,248,82,83,83,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025
14,2,4841617,243,90,80,73,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025
15,3,3950298,243,76,84,83,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025
16,4,3804419,242,82,78,82,0,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025
17,5,3694554,241,70,85,81,5,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025
...,...,...,...,...,...,...,...,...,...
70,58,3940951,203,64,70,69,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025
71,59,3884003,203,58,72,73,0,ИСТ -25-3б,№ 07-08/10-С от 07.08.2025
72,60,4532678,202,74,64,64,0,ИСТ -25-1б,№ 07-08/10-С от 07.08.2025
73,61,4076891,202,55,65,82,0,ИСТ -25-2б,№ 07-08/10-С от 07.08.2025
74,62,4395079,200,70,60,70,0,ИСТ -25-3б,№ 11-08/5-С от 11.08.2025

убираем не нужные столбцы

In [9]:
df = df.drop(columns=["№",	"Уникальный код", "Учебная группа",	"Представление приказа"])
df

,Сумма баллов,АиНМА / Математика,ИТ / Информатика и ИКТ / Физика,Русский язык,Сумма баллов за ИД
13,248,82,83,83,0
14,243,90,80,73,0
15,243,76,84,83,0
16,242,82,78,82,0
17,241,70,85,81,5
...,...,...,...,...,...
70,203,64,70,69,0
71,203,58,72,73,0
72,202,74,64,64,0
73,202,55,65,82,0
74,200,70,60,70,0

переименовать порядковые индексы (drop=True - убирает сохранение старого индекса в отдельном столбце)

In [10]:
df = df.reset_index(drop=True)
df

,Сумма баллов,АиНМА / Математика,ИТ / Информатика и ИКТ / Физика,Русский язык,Сумма баллов за ИД
0,248,82,83,83,0
1,243,90,80,73,0
2,243,76,84,83,0
3,242,82,78,82,0
4,241,70,85,81,5
...,...,...,...,...,...
57,203,64,70,69,0
58,203,58,72,73,0
59,202,74,64,64,0
60,202,55,65,82,0
61,200,70,60,70,0

Проверяем типы данных во всех столбцах

In [11]:
print(df.dtypes)

Сумма баллов                       object
АиНМА / Математика                 object
ИТ / Информатика и ИКТ / Физика    object
Русский язык                       object
Сумма баллов за ИД                 object
dtype: object

приводим к числовому типу (astype - можно если все значения числа)

In [12]:
df = df.astype(int)
print(df.dtypes)

Сумма баллов                       int64
АиНМА / Математика                 int64
ИТ / Информатика и ИКТ / Физика    int64
Русский язык                       int64
Сумма баллов за ИД                 int64
dtype: object

Определить средний, минимальный и максимальный суммарные баллы.

In [13]:
mean_value = df["Сумма баллов"].mean()
min_value = df["Сумма баллов"].min()
max_value = df["Сумма баллов"].max()

print("Средний: ", mean_value)
print("Минимальный: ", min_value)
print("Максимальный: ", max_value)

Средний:  216.83870967741936
Минимальный:  200
Максимальный:  248

Определить средние значения по трем сдаваемым предметам ЕГЭ

In [14]:
data = ["АиНМА / Математика",	"ИТ / Информатика и ИКТ / Физика",	"Русский язык"]
mean_value = df[data].mean()

mean_df = pd.DataFrame(mean_value, columns=["Средний балл"])

mean_df

                                 Средний балл
АиНМА / Математика                  74.387097
ИТ / Информатика и ИКТ / Физика     71.741935
Русский язык                        70.306452

предмет, по которому абитуриенты в среднем набирают больше баллов.

In [15]:
max_mean = mean_df["Средний балл"].max()     # максимальный балл
max_subject = mean_df["Средний балл"].idxmax()    # индекс строки с максимальным баллом 

print("Предмет с максимальным баллом: ", max_subject, max_mean)

Предмет с максимальным баллом:  АиНМА / Математика 74.38709677419355

количество абитуриентов, у которых балла ЕГЭ по русскому ниже
среднего балла по русскому языку, а по остальным предметам выше средних

In [ ]:
mean_math = df["АиНМА / Математика"].mean()
mean_it = df["ИТ / Информатика и ИКТ / Физика"].mean()
mean_russian = df["Русский язык"].mean()

# выборка подходящих значений
type_1 = df[
    (df["Русский язык"]<mean_russian)&(df["АиНМА / Математика"]>mean_math) & (df["ИТ / Информатика и ИКТ / Физика"]>mean_it)]

# кол-во строк подходящих под условия
count_1=len(type_1)

print("количество абитуриентов (тип 1): ", count_1)

количество абитуриентов (тип 1):  6

количество абитуриентов, у которых балла ЕГЭ по русскому выше
среднего балла по русскому языку, а по остальным предметам ниже средних

In [17]:
# выборка подходящих значений
type_2 = df[
    (df["Русский язык"]>mean_russian)&(df["АиНМА / Математика"]<mean_math) & (df["ИТ / Информатика и ИКТ / Физика"]<mean_it)]

# кол-во строк подходящих под условия
count_2=len(type_2)

print("количество абитуриентов (тип 2): ", count_2)

количество абитуриентов (тип 2):  9

итоговая таблица

In [19]:
mean_value_1 = df["Сумма баллов"].mean()

new_df = pd.DataFrame({
    "Подразделение": ["Факультет прикладной математики и механики"],
    "Уровень подготовки": ["Бакалавриат"],
    "Направление подготовки/специальность": ["Информационные системы и технологии"],
    "Год": ["2025"],
    "Количество мест": [len(df)],
    "Предметы ЕГЭ": ["АиНМА / Математика, ИТ / Информатика и ИКТ / Физика, Русский язык"],
    "Средняя сумма баллов": [mean_value_1],
    "Min сумма баллов": [min_value],
    "Max сумма баллов": [max_value],
    "Предмет с высшим средним": [max_subject],
    "Кол-во студентов тип_1": [count_1],
    "Кол-во студентов тип_2": [count_2],
})

# транспонируем таблицу для читаемого вывода
new_df.transpose()

                                                                                      0
Подразделение                                Факультет прикладной математики и механики
Уровень подготовки                                                          Бакалавриат
Направление подготовки/специальность                Информационные системы и технологии
Год                                                                                2025
Количество мест                                                                      62
Предметы ЕГЭ                          АиНМА / Математика, ИТ / Информатика и ИКТ / Ф...
Средняя сумма баллов                                                          216.83871
Min сумма баллов                                                                    200
Max сумма баллов                                                                    248
Предмет с высшим средним                                             АиНМА / Математика
Кол-во студентов тип_1                                                                6
Кол-во студентов тип_2                                                                9