In [18]:
import pandas as pd

df = pd.read_csv("BikeData.csv")
df

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,467,177
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,296,63
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,571,665
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,171,457
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,442,401

1. Создать Total_count (сумма Partner 1 и Partner 2)

In [19]:
df['Total_count'] = df['Partner 1'] + df['Partner 2']

df[['Partner 1', 'Partner 2', 'Total_count']]

      Partner 1  Partner 2  Total_count
0           207         50          257
1           139         80          219
2            22        140          162
3            43        105          148
4            59         38           97
...         ...        ...          ...
8755        467        177          644
8756        296         63          359
8757        571        665         1236
8758        171        457          628
8759        442        401          843

[8760 rows x 3 columns]

2. Удалить колонки Partner 1 и Partner 2

In [20]:
df = df.drop(['Partner 1', 'Partner 2'], axis=1)
df

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,30/11/2018,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,30/11/2018,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,30/11/2018,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,30/11/2018,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,30/11/2018,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

3. Преобразовать переменную Date в datetime. dayfirst=True - парсит даты в формате день-месяц-год, rrors='coerce' - если отказано, то NaN

In [21]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')
df

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97
...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843

4. Сколько велосипедов выдано в день/месяц, число которого совпадает с днём выполнения задания. Какой это день недели?

4.1. Добавляем дополнительные колонки

In [22]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.day_name()

df

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Total_count,Year,Month,Day,Weekday
0,2017-12-01,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,257,2017,12,1,Friday
1,2017-12-01,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,219,2017,12,1,Friday
2,2017-12-01,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,162,2017,12,1,Friday
3,2017-12-01,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,148,2017,12,1,Friday
4,2017-12-01,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,97,2017,12,1,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-11-30,19,4.2,34,2.6,0.0,0.0,Autumn,No Holiday,Yes,644,2018,11,30,Friday
8756,2018-11-30,20,3.4,37,2.3,0.0,0.0,Autumn,No Holiday,Yes,359,2018,11,30,Friday
8757,2018-11-30,21,2.6,39,0.3,0.0,0.0,Autumn,No Holiday,Yes,1236,2018,11,30,Friday
8758,2018-11-30,22,2.1,41,1.0,0.0,0.0,Autumn,No Holiday,Yes,628,2018,11,30,Friday
8759,2018-11-30,23,1.9,43,1.3,0.0,0.0,Autumn,No Holiday,Yes,843,2018,11,30,Friday

4.2. Текущая дата. Timestamp почти то же что datetime.datetime

In [23]:
today = pd.Timestamp.now().date()
today_day = today.day
today_month = today.month

4.3. Фильтруем данные, где совпадают день и месяц

In [24]:
same_day_data = df.loc[
    (df['Day'] == today_day) & (df['Month'] == today_month),
    ['Date', 'Total_count', 'Weekday']
].copy()

4.4. Группируем по году, чтобы увидеть аренды за разные годы в этот день

In [25]:
bikes_by_year = df.loc[
    (df['Day'] == today_day) & (df['Month'] == today_month)
].groupby('Year')['Total_count'].sum().reset_index()

4.5. Определяем день недели сегодняшней даты

In [26]:
weekday_today = pd.Timestamp.now().day_name()

4.6. Вывод результатов

In [27]:
print(f"Сегодня: {today_day:02d}.{today_month:02d}")
print(f"День недели: {weekday_today}")
print("\nКоличество аренд в этот день по разным годам:")
display(bikes_by_year)

print("\nПодробные данные за этот день:")
display(same_day_data)

Сегодня: 14.11
День недели: Friday

Количество аренд в этот день по разным годам:

   Year  Total_count
0  2018        24361

Подробные данные за этот день:

           Date  Total_count    Weekday
8352 2018-11-14          722  Wednesday
8353 2018-11-14          686  Wednesday
8354 2018-11-14          517  Wednesday
8355 2018-11-14          117  Wednesday
8356 2018-11-14          124  Wednesday
8357 2018-11-14           48  Wednesday
8358 2018-11-14          507  Wednesday
8359 2018-11-14         1481  Wednesday
8360 2018-11-14         2004  Wednesday
8361 2018-11-14         1392  Wednesday
8362 2018-11-14          899  Wednesday
8363 2018-11-14          614  Wednesday
8364 2018-11-14          184  Wednesday
8365 2018-11-14          951  Wednesday
8366 2018-11-14         1654  Wednesday
8367 2018-11-14          401  Wednesday
8368 2018-11-14         1198  Wednesday
8369 2018-11-14         1085  Wednesday
8370 2018-11-14         2422  Wednesday
8371 2018-11-14         2076  Wednesday
8372 2018-11-14         1578  Wednesday
8373 2018-11-14         1116  Wednesday
8374 2018-11-14         1640  Wednesday
8375 2018-11-14          945  Wednesday

4.7. Фильтруем данные, где совпадают день и месяц

In [28]:
same_day_data = df.loc[
    (df['Day'] == today_day) & (df['Month'] == today_month),
    ['Date', 'Total_count', 'Weekday']
].copy()
same_day_data

           Date  Total_count    Weekday
8352 2018-11-14          722  Wednesday
8353 2018-11-14          686  Wednesday
8354 2018-11-14          517  Wednesday
8355 2018-11-14          117  Wednesday
8356 2018-11-14          124  Wednesday
8357 2018-11-14           48  Wednesday
8358 2018-11-14          507  Wednesday
8359 2018-11-14         1481  Wednesday
8360 2018-11-14         2004  Wednesday
8361 2018-11-14         1392  Wednesday
8362 2018-11-14          899  Wednesday
8363 2018-11-14          614  Wednesday
8364 2018-11-14          184  Wednesday
8365 2018-11-14          951  Wednesday
8366 2018-11-14         1654  Wednesday
8367 2018-11-14          401  Wednesday
8368 2018-11-14         1198  Wednesday
8369 2018-11-14         1085  Wednesday
8370 2018-11-14         2422  Wednesday
8371 2018-11-14         2076  Wednesday
8372 2018-11-14         1578  Wednesday
8373 2018-11-14         1116  Wednesday
8374 2018-11-14         1640  Wednesday
8375 2018-11-14          945  Wednesday

5. Перекодировать категориальную переменную Functioning Day ("Yes" = True, "No" = False) и посчитать количество нерабочих дней (дней, в которых работало < 12 часов)

In [29]:
# Yes -> True, No -> False
df['Functioning Day'] = df['Functioning Day'].apply(lambda x: True if x == 'Yes' else False)

# Считаем количество часов работы пункта в день
hours_period_day = df.groupby(df['Date'].dt.date)['Functioning Day'].sum().reset_index(name='Hours_open')
display(hours_period_day)

# День считается нерабочим, если работали < 12 часов
hours_period_day['Non_working_day'] = hours_period_day['Hours_open'] < 12
display(hours_period_day)
# Количество нерабочих дней
num_nonworking_days = hours_period_day['Non_working_day'].sum()

print(f"Количество нерабочих дней: {num_nonworking_days}")

           Date  Hours_open
0    2017-12-01          24
1    2017-12-02          24
2    2017-12-03          24
3    2017-12-04          24
4    2017-12-05          24
..          ...         ...
360  2018-11-26          24
361  2018-11-27          24
362  2018-11-28          24
363  2018-11-29          24
364  2018-11-30          24

[365 rows x 2 columns]

           Date  Hours_open  Non_working_day
0    2017-12-01          24            False
1    2017-12-02          24            False
2    2017-12-03          24            False
3    2017-12-04          24            False
4    2017-12-05          24            False
..          ...         ...              ...
360  2018-11-26          24            False
361  2018-11-27          24            False
362  2018-11-28          24            False
363  2018-11-29          24            False
364  2018-11-30          24            False

[365 rows x 3 columns]

Количество нерабочих дней: 12

6. Перекодировать Holiday в 0/1 (используя lambda)

In [30]:
df['Holiday'] = df['Holiday'].apply(lambda x: 1 if x == 'Holiday' else 0)
df[['Date', 'Holiday']]

           Date  Holiday
0    2017-12-01        0
1    2017-12-01        0
2    2017-12-01        0
3    2017-12-01        0
4    2017-12-01        0
...         ...      ...
8755 2018-11-30        0
8756 2018-11-30        0
8757 2018-11-30        0
8758 2018-11-30        0
8759 2018-11-30        0

[8760 rows x 2 columns]

7. Ввести новую категориальную переменную Temperature category ("Freezing", если температура < 0;
"Chilly", если 0 <= температура < 15;
"Nice", если 15 <= температура < 26;
"Hot", если 26 <= температура.)

In [31]:
def temp_category(temp):
    if temp < 0:
        return "Freezing"
    elif 0 <= temp < 15:
        return "Chilly"
    elif 15 <= temp < 26:
        return "Nice"
    else:
        return "Hot"

df['Temperature category'] = df['Temperature'].apply(temp_category)
df[['Temperature', 'Temperature category']]

      Temperature Temperature category
0            -5.2             Freezing
1            -5.5             Freezing
2            -6.0             Freezing
3            -6.2             Freezing
4            -6.0             Freezing
...           ...                  ...
8755          4.2               Chilly
8756          3.4               Chilly
8757          2.6               Chilly
8758          2.1               Chilly
8759          1.9               Chilly

[8760 rows x 2 columns]

8. Создать переменную Good weather (1 = хорошая погода) по заданным условиям (Temperature category = "Nice",
Humidity в диапазоне от 40 до 60 ,
скорость ветра Wind speed меньше 5.4,
нет дождя (Rainfall)
нет снега (Snowfall)).

In [32]:
# Создаем новую колонку Good weather
def good_weather(row):
    if (
        row['Temperature category'] == 'Nice' and
        40 <= row['Humidity'] <= 60 and
        row['Wind speed'] < 5.4 and
        row['Rainfall'] == 0 and
        row['Snowfall'] == 0
    ):
        return 1
    else:
        return 0

df['Good weather'] = df.apply(good_weather, axis=1)

# Считаем процент наблюдений с хорошей погодой
percent_good = df['Good weather'].mean() * 100
print(f"Процент хорошей погоды: {percent_good:.2f}%")

df[['Date', 'Temperature', 'Humidity', 'Wind speed', 'Rainfall', 'Snowfall', 'Temperature category', 'Good weather']].head(10)

Процент хорошей погоды: 9.27%

,Date,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Temperature category,Good weather
0,2017-12-01,-5.2,37,2.2,0.0,0.0,Freezing,0
1,2017-12-01,-5.5,38,0.8,0.0,0.0,Freezing,0
2,2017-12-01,-6.0,39,1.0,0.0,0.0,Freezing,0
3,2017-12-01,-6.2,40,0.9,0.0,0.0,Freezing,0
4,2017-12-01,-6.0,36,2.3,0.0,0.0,Freezing,0
5,2017-12-01,-6.4,37,1.5,0.0,0.0,Freezing,0
6,2017-12-01,-6.6,35,1.3,0.0,0.0,Freezing,0
7,2017-12-01,-7.4,38,0.9,0.0,0.0,Freezing,0
8,2017-12-01,-7.6,37,1.1,0.0,0.0,Freezing,0
9,2017-12-01,-6.5,27,0.5,0.0,0.0,Freezing,0

9. Сгруппировать данные по сезонам и категории температуры

In [33]:
# Через groupby
group = df.groupby(['Seasons', 'Temperature category'])['Total_count'].sum().reset_index()

# Через pivot_table
pivot = df.pivot_table(index='Seasons', columns='Temperature category', values='Total_count', aggfunc='sum', fill_value=0)

print("Группировка через groupby:")
display(group)

print("Сводная таблица через pivot_table:")
display(pivot)

Группировка через groupby:

   Seasons Temperature category  Total_count
0   Autumn               Chilly       775694
1   Autumn             Freezing        12035
2   Autumn                  Hot       170674
3   Autumn                 Nice       811498
4   Spring               Chilly       587211
5   Spring             Freezing         6331
6   Spring                  Hot        86791
7   Spring                 Nice       928572
8   Summer                  Hot      1347262
9   Summer                 Nice       892664
10  Winter               Chilly       215221
11  Winter             Freezing       258570
12  Winter                  Hot         9536

Сводная таблица через pivot_table:

Temperature category  Chilly  Freezing      Hot    Nice
Seasons
Autumn                775694     12035   170674  811498
Spring                587211      6331    86791  928572
Summer                     0         0  1347262  892664
Winter                215221    258570     9536       0

10. Найти сезон и категорию с максимумом и минимумом аренд

In [34]:
max_row = group.loc[group['Total_count'].idxmax()]
min_row = group.loc[group['Total_count'].idxmin()]

print("Максимум аренд:")
print(max_row)

print("Минимум аренд:")
print(min_row)

Максимум аренд:
Seasons                  Summer
Temperature category        Hot
Total_count             1347262
Name: 8, dtype: object
Минимум аренд:
Seasons                   Spring
Temperature category    Freezing
Total_count                 6331
Name: 5, dtype: object