1 задание

In [11]:
import pandas as pd

In [12]:
ratings = pd.read_csv("ml-1m/ratings.dat", sep="::", names=["UserID", "MovieID", "Rating", "Timestamp"], engine="python")
users = pd.read_csv("ml-1m/users.dat", sep="::", names=["UserID", "Gender", "Age", "Occupation", "Zip-code"], engine="python")
movies = pd.read_csv("ml-1m/movies.dat", sep="::", names=["MovieID", "Title", "Genres"], engine="python", encoding="latin-1")

# pd.merge - объединяет по одному/нескольким столбцам или индексам
ratings_users = pd.merge(ratings, users, on="UserID") # по столбцу UserID
general_table = pd.merge(ratings_users, movies, on="MovieID") # по столбцу MovieID
general_table

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title,Genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy
...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi

1. Требуется вычислить средние рейтинги для фильма с ID = № варианта в зависимости
от пола; 44

In [13]:
female=general_table[(general_table["MovieID"]==44) & (general_table["Gender"]=="F")] # булевая фильтрация тру или фолс
print("Средний рейтинг для фильма с ID = 44 для женщин: ", female["Rating"].mean())

man = general_table[(general_table["MovieID"]==44) & (general_table["Gender"]=="M")]
print("Средний рейтинг для фильма с ID = 44 для мужчин: ", man["Rating"].mean())

Средний рейтинг для фильма с ID = 44 для женщин:  2.810810810810811
Средний рейтинг для фильма с ID = 44 для мужчин:  2.7846715328467155

2. Отобрать фильмы, получившие не менее 250 оценок, и для них определить средний
рейтинг в зависимости от пола;
   - count() - подсчитывает количество непустых (не-NaN) значений в каждой колонке или строке

In [14]:
id = general_table.groupby("MovieID")["Rating"].count().reset_index(name="Count Rating") #кол-во оценок для каждого фильма
id

      MovieID  Count Rating
0           1          2077
1           2           701
2           3           478
3           4           170
4           5           296
...       ...           ...
3701     3948           862
3702     3949           304
3703     3950            54
3704     3951            40
3705     3952           388

[3706 rows x 2 columns]

объединение таблиц

In [15]:
general_table = pd.merge(general_table, id, on="MovieID")
general_table

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title,Genres,Count Rating
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama,1725
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical,525
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance,636
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama,1315
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy,1703
...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy,373
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War,1229
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama,478
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama,344
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,2269

фильмы с кол-вом оценок более 250

In [16]:
count_rating_250 = general_table[general_table["Count Rating"] >= 250]
count_rating_250

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title,Genres,Count Rating
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama,1725
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical,525
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance,636
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama,1315
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy,1703
...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy,373
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War,1229
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama,478
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama,344
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,2269

In [17]:
average_rating = count_rating_250.groupby(["MovieID", "Title", "Gender"])["Rating"].mean().reset_index()
average_rating

      MovieID                       Title Gender    Rating
0           1            Toy Story (1995)      F  4.187817
1           1            Toy Story (1995)      M  4.130552
2           2              Jumanji (1995)      F  3.278409
3           2              Jumanji (1995)      M  3.175238
4           3     Grumpier Old Men (1995)      F  3.073529
...       ...                         ...    ...       ...
2427     3948     Meet the Parents (2000)      M  3.641838
2428     3949  Requiem for a Dream (2000)      F  3.950000
2429     3949  Requiem for a Dream (2000)      M  4.174107
2430     3952       Contender, The (2000)      F  3.761905
2431     3952       Contender, The (2000)      M  3.787986

[2432 rows x 4 columns]

In [29]:
rating = average_rating.pivot_table(index=["MovieID", "Title"], columns="Gender", values="Rating")
rating.columns = ["Rating_F", "Rating_M"]
rating.reset_index()

      MovieID                               Title  Rating_F  Rating_M
0           1                    Toy Story (1995)  4.187817  4.130552
1           2                      Jumanji (1995)  3.278409  3.175238
2           3             Grumpier Old Men (1995)  3.073529  2.994152
3           5  Father of the Bride Part II (1995)  3.212963  2.888298
4           6                         Heat (1995)  3.682171  3.909988
...       ...                                 ...       ...       ...
1211     3917                   Hellraiser (1987)  3.022222  3.128205
1212     3927             Fantastic Voyage (1966)  3.535714  3.589041
1213     3948             Meet the Parents (2000)  3.619048  3.641838
1214     3949          Requiem for a Dream (2000)  3.950000  4.174107
1215     3952               Contender, The (2000)  3.761905  3.787986

[1216 rows x 4 columns]

3. Найти фильмы, оказавшиеся в топ 5 у зрителей-женщин и худшие 5 у зрителей-
мужчин. Найти фильмы (топ 5), по которым мужчины и женщины сильнее всего
разошлись в оценках;

In [19]:
top_rating = general_table.pivot_table(index="Title", columns="Gender", values="Rating", aggfunc="mean").reset_index()
top_rating

Gender                                       Title         F         M
0                           $1,000,000 Duck (1971)  3.375000  2.761905
1                             'Night Mother (1986)  3.388889  3.352941
2                        'Til There Was You (1997)  2.675676  2.733333
3                               'burbs, The (1989)  2.793478  2.962085
4                    ...And Justice for All (1979)  3.828571  3.689024
...                                            ...       ...       ...
3701                   Zed & Two Noughts, A (1985)  3.500000  3.380952
3702                            Zero Effect (1998)  3.864407  3.723140
3703    Zero Kelvin (Kjærlighetens kjøtere) (1995)       NaN  3.500000
3704                       Zeus and Roxanne (1997)  2.777778  2.357143
3705                               eXistenZ (1999)  3.098592  3.289086

[3706 rows x 3 columns]

топ 5 у зрителей-женщин

In [20]:
female_top_5 = top_rating.sort_values(by="F", ascending=False)
female_top_5["Title"].iloc[:5].reset_index()

   index                                 Title
0     18        24 7: Twenty Four Seven (1997)
1   1297    Gate of Heavenly Peace, The (1995)
2    381                 Big Combo, The (1955)
3    836                     Dancemaker (1998)
4    703  Clean Slate (Coup de Torchon) (1981)

худшие 5 у зрителей-мужчин

In [21]:
man_worst_5 = top_rating.sort_values(by="M", ascending=True)
man_worst_5["Title"].iloc[:5].reset_index()

   index                                              Title
0   3552                         Waltzes from Vienna (1933)
1   1063  Even Dwarfs Started Small (Auch Zwerge haben k...
2   1033                             Elstree Calling (1930)
3   3609                                  White Boys (1999)
4   3491                         Uninvited Guest, An (2000)

Найти фильмы (топ 5), по которым мужчины и женщины сильнее всего разошлись в оценках

In [22]:
top_rating["F"] = top_rating["F"].fillna(0) # заменяем NAN на 0
top_rating["M"] = top_rating["M"].fillna(0) # заменяем NAN на 0

top_rating["diff"] = abs(top_rating["F"] - top_rating["M"])

top_rating = top_rating.sort_values(by="diff", ascending=False)
top_rating[["Title", "F", "M","diff"]].iloc[:5].reset_index()

Gender  index                     Title    F    M  diff
0        3044      Smashing Time (1967)  0.0  5.0   5.0
1        2453  One Little Indian (1973)  5.0  0.0   5.0
2        2025              Lured (1947)  0.0  5.0   5.0
3        3477   Ulysses (Ulisse) (1954)  0.0  5.0   5.0
4        1203   Follow the Bitch (1998)  0.0  5.0   5.0

4. Определить фильмы (топ 5), вызвавшие в среднем наибольшее разногласие у зрителей независимо от пола;

Стандартное отклонение (std), показывает разброс данных относительно среднего значения

In [23]:
std_rating = general_table.groupby("Title")["Rating"].std().reset_index(name="std_rating")

std_rating_5 = std_rating.sort_values(by="std_rating", ascending=False)
std_rating_5.iloc[:5].reset_index()

   index                                              Title  std_rating
0   1223                             Foreign Student (1994)    2.828427
1    791      Criminal Lovers (Les Amants Criminels) (1999)    2.309401
2   2338                             Neon Bible, The (1995)    2.121320
3   2513  Paralyzing Fear: The Story of Polio in America...    2.121320
4   3385                                  Tokyo Fist (1995)    2.121320

5. Определить средний рейтинг каждого жанра для различных возрастов. Установите,
фильмы какого жанра в каждой категории возрастов имеют наибольший и наименьший
рейтинги.
   - str - применяем split к каждой строке текущего столбца

In [24]:
general_table["Genres"] = general_table["Genres"].str.split("|")
general_table = general_table.explode("Genres") # разбиваем на строки для каждого жарна
general_table

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title,Genres,Count Rating
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama,1725
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation,525
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Children's,525
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Musical,525
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical,636
...,...,...,...,...,...,...,...,...,...,...,...
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama,344
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's,2269
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Drama,2269
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Fantasy,2269
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Sci-Fi,2269

In [25]:
general_table_genres = general_table.groupby(["Age", "Genres"])["Rating"].mean().reset_index()
general_table_genres

     Age      Genres    Rating
0      1      Action  3.506385
1      1   Adventure  3.449975
2      1   Animation  3.476113
3      1  Children's  3.241642
4      1      Comedy  3.497491
..   ...         ...       ...
121   56     Romance  3.816531
122   56      Sci-Fi  3.497746
123   56    Thriller  3.719749
124   56         War  4.067285
125   56     Western  3.792198

[126 rows x 3 columns]

наибольший рейтинг

In [26]:
age_table_max = general_table_genres.groupby("Age")["Rating"].max().reset_index()

max_rating = pd.merge(general_table_genres, age_table_max, on=["Age", "Rating"])
max_rating

   Age     Genres    Rating
0    1  Film-Noir  4.145455
1   18  Film-Noir  3.997368
2   25  Film-Noir  4.058725
3   35  Film-Noir  4.064910
4   45  Film-Noir  4.105376
5   50  Film-Noir  4.175401
6   56  Film-Noir  4.125932

наименьший рейтинг

In [27]:
age_table_min = general_table_genres.groupby("Age")["Rating"].min().reset_index()

min_rating = pd.merge(general_table_genres, age_table_min, on=["Age", "Rating"])
min_rating

   Age      Genres    Rating
0    1  Children's  3.241642
1   18      Horror  3.172682
2   25      Horror  3.200096
3   35      Horror  3.276022
4   45      Horror  3.262274
5   50      Horror  3.158940
6   56      Horror  3.254401